---
title: "investment_tidytuesday"
author: "Cristal Rivera Picado"
date: "13/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}

library(tidyverse)
library(tidytuesdayR)
library(scales)
library(lubridate)
library(RColorBrewer)

theme_set(theme_light())
library(RColorBrewer)
```


# Cargando los datos

```{r Load}
tuesdata <- tidytuesdayR::tt_load('2021-08-10')
tuesdata <- tidytuesdayR::tt_load(2021, week = 33)

investment <- tuesdata$investment

```

#exploratory 

Count distinct category and meta_cat

```{r}
investment %>% 
  group_by(category) %>% 
  count(sort = TRUE) 
  
```
```{r}
investment %>% 
  group_by(meta_cat) %>% 
  count(sort = TRUE) 
  
```
```{r}
summary(investment$gross_inv)
```

```{r}
top_100 <-investment %>% 
  group_by(meta_cat,year) %>% 
  summarise(Gross_Investment = sum(gross_inv)) %>% 
  filter(year > 2000 & Gross_Investment >= 13418.5) 
top_100 <- top_100[order(-top_100$Gross_Investment),] %>% 
  head(100)
  

View(top_100)
```


```{r}
ggplot(top_100, aes(x = year, y = Gross_Investment)) + 
  geom_line(aes(color = meta_cat), size = 1) +
 
  scale_x_continuous(breaks = seq(2002,2017,3))+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
  theme_dark() +
  labs(color = "Categoría de inversión")+
  scale_colour_brewer(palette = "Set2",direction = 1) +
  xlab("Años")+
  ylab("Inversión bruta en millones de $")+
  ggtitle("Crecimiento de inversión bruta por categoría de grupo de inversión") 
  

```